---
title: "Homework 2"
subtitle: "STT 465, Bayesian Statistical Methods"
date: "September 19, 2025"
author: "Lowell Monis"
output:
  pdf_document:
    toc: false
---


```{r global_options, echo=FALSE, warning = FALSE, results = 'hide', message=FALSE}
library(knitr)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE
)
```

## Question 1

Suppose that if $\theta=1$, then $y$ has a normal distribution with mean 1 and standard deviation $\sigma$, and if $\theta=2$, then $y$ has a normal distribution with mean 2 and standard deviation $\sigma$. Also suppose that $P(\theta=1)=0.5=P(\theta=2)$.

### (a) 5 points

For $\sigma=2$, write the formula for the marginal probability density for $y$. Then draw the density curve of $y$.

### Answer



### (b) 5 points

What is $P(\theta=1|y=1)$ for $\sigma=2$.

### Answer



### (c) 10 points

Describe how the posterior density of $\theta$ changes in shape as $\theta$ is increasing and as it is decreased.

### Answer



## Question 2

Logan (1983) reported the following joint density on $(Y_1,Y_2)=(\text{Father’s Occupation, Son’s Occupation})$:

| Father's Occupation | Son's Occupation | | | | |
| :--- | :--- | :--- | :--- | :--- | :--- |
| | farm | operatives | craftsmen | sales | professional |
| farm | 0.018 | 0.035 | 0.031 | 0.008 | 0.018 |
| operatives | 0.002 | 0.112 | 0.064 | 0.032 | 0.069 |
| craftsmen | 0.001 | 0.066 | 0.094 | 0.032 | 0.084 |
| sales | 0.001 | 0.018 | 0.019 | 0.010 | 0.051 |
| professional | 0.001 | 0.029 | 0.032 | 0.043 | 0.130 |

Use the joint density to calculate the following:

### (a) 5 points

The marginal density for a father’s occupation.

### Answer



### (b) 5 points

The marginal density for a son’s occupation.

### Answer



### (c) 5 points

The conditional density of a son’s occupation given that the father’s occupation is a craftsman.

### Answer


## Question 3

Suppose that $X$ and $Y$ are random variables with joint density function:

$$f_{X,Y}(x,y)=\begin{cases}\frac{1}{4}(x+y), &0\leq x\leq y\leq2\\0,&\text{otherwise}\end{cases}$$

### (a) 5 points

Check that $f_{X,Y}$ is a joint density function.

### Answer



### (b) 5 points

Calculate the probability $P\{Y<2X\}$.

### Answer



### (c) 10 points

Find the marginal density function $f_Y(y)$ of Y.

### Answer



## Question 4 (5 points)

Suppose $X\sim\text{Beta}(a,b)$. Derive $E(X^2)$.

### Answer




***